"""D2.3 -- stratified allocation and estimation, checked against R survey.

Every expected number here comes from `r/fixtures/stratified.json`, which was
generated by R survey 4.5 in a digest-pinned image and committed in `41f8a33`,
before any of the code under test existed. R2.2.

That ordering is the point of the whole phase. A test cannot agree with an
implementation for the same wrong reason when the expected value predates the
implementation.

R2.3: agreement to at least 4 significant digits, or the build is red. In
practice these agree to about 1e-15.

Every gate gets both controls. A gate that refuses everything proves nothing.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, cast

import pytest

from prevalence_kit.errors import Reason, Refusal
from prevalence_kit.stratified import (
    Rounding,
    Stratum,
    allocate,
    largest_remainder,
    neyman_raw,
    stratified_estimate,
)

FIXTURE = Path(__file__).resolve().parents[1] / "r" / "fixtures" / "stratified.json"


def fixtures() -> dict[str, Any]:
    parsed: dict[str, Any] = json.loads(FIXTURE.read_text(encoding="utf-8"))
    return parsed


def allocation_fixture(label: str) -> dict[str, Any]:
    for entry in fixtures()["allocation_fixtures"]:
        if entry["label"] == label:
            return dict(entry)
    raise AssertionError(f"no allocation fixture named {label}")


def estimation_fixture(label: str) -> dict[str, Any]:
    for entry in fixtures()["estimation_fixtures"]:
        if entry["label"] == label:
            return dict(entry)
    raise AssertionError(f"no estimation fixture named {label}")


def as_list(value: Any) -> list[Any]:
    return list(value) if isinstance(value, list) else [value]


def strata_from(weights: list[float], rates: list[float], frame: int) -> tuple[Stratum, ...]:
    """Build strata whose sizes give exactly the fixture's weights."""
    return tuple(
        Stratum(name=f"s{i}", size=round(w * frame), variance_proxy=p)
        for i, (w, p) in enumerate(zip(weights, rates, strict=True))
    )


def relative(got: float, want: float) -> float:
    return abs(got - want) / abs(want) if want else abs(got)


# ------------------------------------------------------------------ allocation


@pytest.mark.parametrize("label", ["barnett_neyman_4000", "rare_event_neyman_5000"])
def test_neyman_raw_matches_the_r_fixture(label: str) -> None:
    """The un-rounded allocation, against numbers R produced first."""
    fixture = allocation_fixture(label)
    strata = strata_from(as_list(fixture["W_h"]), as_list(fixture["p_h"]), 1_000_000)

    got = neyman_raw(strata, fixture["n_total"])
    want = as_list(fixture["result"]["raw"])

    assert len(got) == len(want)
    for ours, theirs in zip(got, want, strict=True):
        assert relative(ours, theirs) < 1e-4, f"{ours} vs {theirs}"


def test_barnett_allocation_reproduces_the_published_table() -> None:
    """S-2.3. The published figures, not a fixture we generated.

    2098 / 828 / 584 / 256 / 234, from Barnett Table 2B. If this fails, the
    specification has moved and the anchor no longer holds.
    """
    fixture = allocation_fixture("barnett_neyman_4000")
    strata = strata_from(as_list(fixture["W_h"]), as_list(fixture["p_h"]), 1_000_000)

    result = allocate(strata, 4000, Rounding.LARGEST_REMAINDER)

    assert result.units == (2098, 828, 584, 256, 234)
    assert result.total == 4000


def test_largest_remainder_fixes_the_case_that_did_not_sum() -> None:
    """Q4's actual failing case, and the reason D-30 exists.

    rare_event asks for 5000. Flooring gives 3845/884/270 = 4999. The largest
    fractional part is stratum 1's 0.4104, so stratum 1 takes the unit.
    """
    fixture = allocation_fixture("rare_event_neyman_5000")
    raw = tuple(as_list(fixture["result"]["raw"]))

    floored = tuple(int(x) for x in raw)
    assert sum(floored) == 4999, "the fixture no longer carries the short case"

    rounded = largest_remainder(raw, 5000)
    assert sum(rounded) == 5000
    assert rounded == (3846, 884, 270)


def test_largest_remainder_pinned_against_a_recorded_value() -> None:
    """D-30 condition 2. The tie-break, locked.

    Three strata with identical fractional parts of exactly 0.5 and two units to
    hand out. The rule is: ties go to the lowest stratum index -- the order the
    plan lists them in.

    If someone later sorts by name, by size, or by whatever order a dict
    happened to have, this fails and they have to say why. That is the same
    reason `test_draw_pinned_against_a_recorded_value` exists for the keyed sort.
    """
    raw = (1.5, 2.5, 3.5)
    assert sum(raw) == 7.5
    # Floors are 1/2/3 and sum to 6, so the shortfall is n - 6 at each step.
    assert largest_remainder(raw, 6) == (1, 2, 3)  # nothing spare: everyone floors
    assert largest_remainder(raw, 7) == (2, 2, 3)  # one spare: LOWEST index wins
    assert largest_remainder(raw, 8) == (2, 3, 3)  # two spare: indices 0 and 1
    assert largest_remainder(raw, 9) == (2, 3, 4)  # three spare: all round up

    # With unequal fractions the index is irrelevant -- only the fraction ranks.
    # Floors 0/1/2 sum to 3; fractions are 0.9, 0.1, 0.0.
    assert largest_remainder((0.9, 1.1, 2.0), 4) == (1, 1, 2)  # one spare -> biggest fraction
    assert largest_remainder((0.9, 1.1, 2.0), 5) == (1, 2, 2)  # two spare -> next biggest


def test_rounding_is_a_required_argument_not_a_default() -> None:
    """D-30 condition 1, at the API. The rule cannot be a constant in the source."""
    import inspect

    signature = inspect.signature(allocate)
    assert signature.parameters["rounding"].default is inspect.Parameter.empty


# ---------------------------------------------------------- allocation refusals


def test_a_thin_stratum_is_refused_after_rounding_not_before() -> None:
    """Q2 and D-30 condition 4, together.

    The fixture's Q2 case: Neyman gives stratum 2 a raw 0.281, which rounds to
    zero. The refusal has to fire on the rounded number.
    """
    case = fixtures()["q2_floor_case"]
    strata = strata_from(as_list(case["W_h"]), as_list(case["p_h"]), 1_000_000)

    with pytest.raises(Refusal) as caught:
        allocate(strata, case["n_total"], Rounding.LARGEST_REMAINDER)

    assert caught.value.reason is Reason.ALLOCATION_TOO_THIN
    # The statistical reason travels in the operator message, not only the code.
    assert "degrees of freedom" in caught.value.detail
    assert "s1" in caught.value.detail  # names the stratum
    assert "label budget" in caught.value.fix


def test_a_workable_plan_is_accepted() -> None:
    """The positive control for the refusal above."""
    fixture = allocation_fixture("barnett_neyman_4000")
    strata = strata_from(as_list(fixture["W_h"]), as_list(fixture["p_h"]), 1_000_000)

    result = allocate(strata, 4000, Rounding.LARGEST_REMAINDER)
    assert min(result.units) >= 2


def test_no_strata_is_refused_by_name() -> None:
    with pytest.raises(Refusal) as caught:
        allocate((), 100, Rounding.LARGEST_REMAINDER)
    assert caught.value.reason is Reason.STRATA_UNDEFINED


def test_an_empty_stratum_is_refused_by_name() -> None:
    """Distinct from STRATUM_UNSAMPLED: this one sends you to the frame. D-22."""
    strata = (Stratum("full", 100, 0.1), Stratum("empty", 0, 0.1))
    with pytest.raises(Refusal) as caught:
        allocate(strata, 50, Rounding.LARGEST_REMAINDER)
    assert caught.value.reason is Reason.STRATUM_EMPTY
    assert "empty" in caught.value.detail


def test_a_frame_smaller_than_the_sample_is_refused() -> None:
    strata = (Stratum("a", 10, 0.1), Stratum("b", 10, 0.1))
    with pytest.raises(Refusal) as caught:
        allocate(strata, 500, Rounding.LARGEST_REMAINDER)
    assert caught.value.reason is Reason.FRAME_TOO_SMALL


def test_zero_variance_everywhere_is_refused_rather_than_divided_by() -> None:
    """Every rate at 0 makes Neyman's denominator vanish. Arithmetic, not opinion."""
    strata = (Stratum("a", 100, 0.0), Stratum("b", 100, 0.0))
    with pytest.raises(Refusal) as caught:
        allocate(strata, 50, Rounding.LARGEST_REMAINDER)
    assert caught.value.reason is Reason.ALLOCATION_IMPOSSIBLE
    assert "divides by zero" in caught.value.detail


# ------------------------------------------------------------------ estimation


@pytest.mark.parametrize(
    "label",
    [
        "barnett_design",
        "two_stratum_balanced",
        "rare_event",
        "one_stratum_zero_positives",
        "minimum_viable_stratum",
    ],
)
def test_the_estimate_matches_r_survey(label: str) -> None:
    """R2.3. Point estimate and standard error, against survey 4.5.

    These five cover the Barnett design, a balanced pair, the rare-event regime
    this tool exists for, a stratum with no positives at all, and a stratum at
    exactly Q2's floor of two units.
    """
    fixture = estimation_fixture(label)

    got = stratified_estimate(
        weights=tuple(as_list(fixture["W_h"])),
        positives=tuple(int(k) for k in as_list(fixture["k_h"])),
        sampled=tuple(int(n) for n in as_list(fixture["n_h"])),
    )

    assert relative(got.point, fixture["estimate"]) < 1e-4, (
        f"{label}: point {got.point} vs survey's {fixture['estimate']}"
    )
    assert relative(got.standard_error, fixture["se"]) < 1e-4, (
        f"{label}: se {got.standard_error} vs survey's {fixture['se']}"
    )
    assert got.n == fixture["n_total"]


def test_the_estimator_agrees_with_survey_far_beyond_the_required_four_digits() -> None:
    """R2.3 asks for 4 significant digits. Recorded here is what we actually get.

    Stated as a measured figure rather than a claim, because a number nobody
    re-derives is how three corrections happened.
    """
    worst = 0.0
    for fixture in fixtures()["estimation_fixtures"]:
        got = stratified_estimate(
            weights=tuple(as_list(fixture["W_h"])),
            positives=tuple(int(k) for k in as_list(fixture["k_h"])),
            sampled=tuple(int(n) for n in as_list(fixture["n_h"])),
        )
        worst = max(
            worst,
            relative(got.point, fixture["estimate"]),
            relative(got.standard_error, fixture["se"]),
        )
    assert worst < 1e-12, f"worst relative disagreement with survey: {worst:.3e}"


def test_no_finite_population_correction_is_applied() -> None:
    """S-2.3's other half, and the one most easily got wrong.

    An fpc would shrink the standard error whenever the sample is a large share
    of the frame. Here the sample IS the frame, so an fpc would drive the SE to
    zero. It does not, because there is no fpc.
    """
    got = stratified_estimate(weights=(1.0,), positives=(5,), sampled=(10,))
    assert got.standard_error > 0.0


# ---------------------------------------------------------- estimation refusals


def test_an_unsampled_stratum_is_refused_by_name() -> None:
    """Distinct from STRATUM_EMPTY: this one sends you to the sample. D-22."""
    with pytest.raises(Refusal) as caught:
        stratified_estimate(weights=(0.5, 0.5), positives=(3, 0), sampled=(100, 0))
    assert caught.value.reason is Reason.STRATUM_UNSAMPLED


def test_a_single_unit_stratum_is_refused_at_estimate_time_too() -> None:
    """The second net. Q2 refuses at sample time; a hand-built record gets here."""
    with pytest.raises(Refusal) as caught:
        stratified_estimate(weights=(0.5, 0.5), positives=(3, 1), sampled=(100, 1))
    assert caught.value.reason is Reason.ALLOCATION_TOO_THIN


def test_mismatched_lengths_are_refused_by_name() -> None:
    with pytest.raises(Refusal) as caught:
        stratified_estimate(weights=(0.5, 0.5), positives=(3,), sampled=(100, 100))
    assert caught.value.reason is Reason.LABELS_UNMATCHED


def test_a_well_formed_stratified_estimate_is_accepted() -> None:
    """The positive control for the four refusals above."""
    got = stratified_estimate(weights=(0.9, 0.1), positives=(25, 100), sampled=(500, 500))
    assert 0.0 < got.point < 1.0
    assert got.standard_error > 0.0
    assert got.degrees_of_freedom == 998


# ---------------------------------------------------------------- the record


def test_both_allocations_reach_the_record() -> None:
    """D-30 condition 3. Raw and final, so an outsider can redo the rounding.

    With only the final numbers they would have to trust that the rounding was
    done as the plan says. With both, they can check it.
    """
    fixture = allocation_fixture("rare_event_neyman_5000")
    strata = strata_from(as_list(fixture["W_h"]), as_list(fixture["p_h"]), 1_000_000)
    record = allocate(strata, 5000, Rounding.LARGEST_REMAINDER).as_record()

    raw = [float(x) for x in cast("list[str]", record["raw"])]
    units = cast("list[int]", record["units"])
    total = cast("int", record["total"])

    assert record["rule"] == "largest_remainder"
    assert units == [3846, 884, 270]
    assert raw != [float(u) for u in units]
    assert total == 5000

    # An outsider can re-derive the final numbers from the raw ones alone.
    assert list(largest_remainder(tuple(raw), total)) == units
