"""Stratified sampling: Neyman allocation, largest-remainder rounding, and the
stratified estimator.

Anchors, all pinned in docs/STANDARDS.md before any of this was written:

  S-1.2  Neyman (1934) -- optimal allocation
  S-1.3  Cochran, Sampling Techniques, 3rd ed.
  S-1.7  Wright (2014), U.S. Census Bureau RRS #2014-07 -- the rounding rule
  S-2.3  Barnett (2021) Table 2B -- the reproduction that fixes the specification

The specification is pinned by reproduction, not by intention (S-2.3):

  allocation   n_h proportional to W_h * sqrt(p_h(1-p_h))
  variance     Var = sum W_h^2 * s_h^2 / n_h
               WITH REPLACEMENT, NO finite-population correction

That last line is the half most easily got wrong, and it is what reproduces
Barnett's published 0.054 pp.

Every number here was checked against a fixture that existed first --
`r/fixtures/stratified.json`, generated by R survey 4.5 in a digest-pinned image
through the one call D2.1 validated against Barnett. R2.2: a test cannot agree
with an implementation for the same wrong reason when the expected value
predates the implementation.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from math import floor, sqrt

from .canonical import JSONObject
from .errors import Reason, Refusal

MIN_UNITS_PER_STRATUM = 2
"""Q2's floor. A stratum with one unit has zero within-stratum degrees of
freedom, so its variance contribution is undefined -- not small, undefined."""


class Rounding(StrEnum):
    """How a fractional allocation becomes whole units.

    One member today. It is an enum and not a boolean because the plan names it
    (D-30 condition 1), and a named commitment needs a vocabulary that can grow
    without changing the meaning of plans already written.
    """

    LARGEST_REMAINDER = "largest_remainder"


@dataclass(frozen=True, slots=True)
class Stratum:
    """One stratum of the frame, as the plan defines it."""

    name: str
    size: int
    """Units in the frame, not in the sample. The denominator of W_h."""
    variance_proxy: float
    """p_h, the expected rate used only to allocate. Never the estimate."""


@dataclass(frozen=True, slots=True)
class Allocation:
    """What `sample` will draw, and enough to re-derive it without this code."""

    rule: Rounding
    strata: tuple[str, ...]
    weights: tuple[float, ...]
    raw: tuple[float, ...]
    """Pre-rounding, carried so an outsider can redo the rounding themselves."""
    units: tuple[int, ...]
    total: int

    def as_record(self) -> JSONObject:
        """Both allocations reach the ledger. D-30 condition 3.

        Raw and final. With only the final numbers an outsider has to trust that
        the rounding was done as the plan says; with both, they can redo it.
        """
        return {
            "rule": str(self.rule),
            "strata": list(self.strata),
            "weights": [f"{w:.12f}" for w in self.weights],
            "raw": [f"{r:.12f}" for r in self.raw],
            "units": list(self.units),
            "total": self.total,
        }


def neyman_raw(strata: tuple[Stratum, ...], n: int) -> tuple[float, ...]:
    """Neyman allocation, before rounding. S-1.2, specification pinned by S-2.3.

        n_h proportional to W_h * sqrt(p_h(1 - p_h))

    Returns floats on purpose. Rounding is a separate, named, pre-registered
    step -- D-30 -- and fusing the two would hide the decision the plan is
    supposed to carry.
    """
    frame_total = sum(s.size for s in strata)
    weights = [s.size / frame_total for s in strata]
    spread = [sqrt(s.variance_proxy * (1 - s.variance_proxy)) for s in strata]

    denominator = sum(w * d for w, d in zip(weights, spread, strict=True))
    if denominator <= 0:
        raise Refusal(
            Reason.ALLOCATION_IMPOSSIBLE,
            "Every stratum has an expected rate of 0 or 1, so Neyman allocation "
            "divides by zero: there is no variance anywhere to allocate against.",
            "Use proportional allocation, or give at least one stratum a rate "
            "strictly between 0 and 1.",
        )
    return tuple(n * (w * d) / denominator for w, d in zip(weights, spread, strict=True))


def largest_remainder(raw: tuple[float, ...], n: int) -> tuple[int, ...]:
    """Round a fractional allocation to whole units so the total is exactly n.

    The survey-sampling literature calls this **controlled rounding**. Wright
    (2014), S-1.7, section 1, verbatim:

        "In the allocation of the overall sample to the various strata, one may
        frequently need to round to integer values. The issue is often handled
        by controlled rounding. This is done by sorting fractional parts
        (non-integer remainders) from the largest to smallest and assigning the
        desired number of additional units to the strata with the largest
        fractional parts."

    THE TIE-BREAK, stated because equal fractional parts have to resolve the
    same way on every machine and in any language (D-30 condition 2):

        ties go to the LOWEST STRATUM INDEX -- the order the plan lists them in.

    Not by name, not by size, not by whatever order a dict happened to have.
    The plan's own order is the only thing an outsider reading the plan can see.
    Pinned by `test_largest_remainder_pinned_against_a_recorded_value`.

    Reimplementable in a few lines by anyone, which is the bar D-16's keyed sort
    was chosen to meet and the reason this rule was ruled over the alternatives.

    TWO LIMITS, disclosed rather than discovered later. Both are in
    docs/STANDARDS.md under S-1.7 with their evidence:

    1. This is not always the variance-minimal integer allocation. Wright's own
       abstract: "Neyman allocation with rounded integers does not always lead
       to the optimal allocation." His exact-optimal algorithms do better and
       are recorded as the alternative not taken in D-30.
    2. It is not monotone in n. Raising the total sample size can lower a
       stratum's allocation -- 303 such n in 10..6000 on Barnett's own frame.
       For a single pre-registered n this never bites, because the plan fixes n
       before any data is touched and there is no second allocation to be
       inconsistent with.
    """
    base = [floor(x) for x in raw]
    shortfall = n - sum(base)
    if shortfall < 0:
        raise Refusal(
            Reason.ALLOCATION_IMPOSSIBLE,
            f"The floored allocation already totals {sum(base)}, more than the "
            f"{n} units asked for.",
            "This should not happen with a Neyman allocation. Check the plan's "
            "sample_size and stratum definitions.",
        )

    # Sort by fractional part descending, then by index ascending. The index is
    # the tie-break, and `sorted` is stable, so equal keys keep plan order.
    order = sorted(range(len(raw)), key=lambda i: (-(raw[i] - base[i]), i))
    for index in order[:shortfall]:
        base[index] += 1
    return tuple(base)


def allocate(strata: tuple[Stratum, ...], n: int, rounding: Rounding) -> Allocation:
    """Allocate n units across the strata, and refuse when the result is undefined.

    ORDER OF OPERATIONS, and it is not obvious (D-30 condition 4):

        allocate  ->  round  ->  THEN check Q2's floor

    Largest-remainder rounding can still leave a stratum at 0 or 1, so
    ALLOCATION_TOO_THIN has to fire on the rounded numbers. Checking the raw
    floats first would pass a stratum at 1.6 that rounds to 1.

    `rounding` is a required argument with no default. D-30 condition 1: the
    rounding rule is a commitment the operator makes in the plan, and a default
    here would let it be a constant in the source instead.
    """
    if not strata:
        raise Refusal(
            Reason.STRATA_UNDEFINED,
            "The plan asks for a stratified design but defines no strata.",
            "Add a `strata` block to the plan, or use `design: simple_random`.",
        )
    for stratum in strata:
        if stratum.size <= 0:
            raise Refusal(
                Reason.STRATUM_EMPTY,
                f"Stratum '{stratum.name}' is defined but contains no frame units.",
                "Check the population file: this stratum matched nothing. Remove "
                "it from the plan, or fix the frame.",
            )
        if not 0.0 <= stratum.variance_proxy <= 1.0:
            raise Refusal(
                Reason.ALLOCATION_IMPOSSIBLE,
                f"Stratum '{stratum.name}' has an expected rate of "
                f"{stratum.variance_proxy}, which is not a proportion.",
                "Expected rates must be between 0 and 1.",
            )

    frame_total = sum(s.size for s in strata)
    if n > frame_total:
        raise Refusal(
            Reason.FRAME_TOO_SMALL,
            f"The plan asks for {n} units and the strata hold {frame_total}.",
            "Lower sample_size, or supply a larger frame.",
        )

    raw = neyman_raw(strata, n)
    if rounding is not Rounding.LARGEST_REMAINDER:  # pragma: no cover - enum has one member
        raise Refusal(
            Reason.ALLOCATION_ROUNDING_UNDECLARED,
            f"Unknown rounding rule '{rounding}'.",
            f"Use one of: {', '.join(str(r) for r in Rounding)}.",
        )
    units = largest_remainder(raw, n)

    # Now, and only now, Q2's floor.
    thin = [(s.name, u) for s, u in zip(strata, units, strict=True) if u < MIN_UNITS_PER_STRATUM]
    if thin:
        detail = "; ".join(f"'{name}' was allocated {count}" for name, count in thin)
        raise Refusal(
            Reason.ALLOCATION_TOO_THIN,
            f"{detail}. A stratum allocated fewer than {MIN_UNITS_PER_STRATUM} units "
            "has zero degrees of freedom within that stratum, so its variance "
            "contribution is undefined. That is why two is the floor.",
            "Raise sample_size, or merge the thin stratum into a neighbour, then "
            "re-run plan. Fixing it now costs nothing; fixing it after labelling "
            "costs the label budget.",
        )

    for stratum, count in zip(strata, units, strict=True):
        if count > stratum.size:
            raise Refusal(
                Reason.ALLOCATION_IMPOSSIBLE,
                f"Stratum '{stratum.name}' was allocated {count} units but holds "
                f"only {stratum.size}.",
                "Neyman allocation can exceed a small stratum's size. Lower "
                "sample_size, or merge this stratum into a neighbour.",
            )

    return Allocation(
        rule=rounding,
        strata=tuple(s.name for s in strata),
        weights=tuple(s.size / frame_total for s in strata),
        raw=raw,
        units=units,
        total=sum(units),
    )


@dataclass(frozen=True, slots=True)
class StratifiedEstimate:
    """A stratified point estimate and its standard error."""

    point: float
    standard_error: float
    n: int
    positives: int
    degrees_of_freedom: int


def stratified_estimate(
    weights: tuple[float, ...],
    positives: tuple[int, ...],
    sampled: tuple[int, ...],
) -> StratifiedEstimate:
    """The stratified mean and its standard error.

        p_hat  = sum W_h * p_hat_h
        Var    = sum W_h^2 * s_h^2 / n_h,   s_h^2 = n_h/(n_h - 1) * p(1-p)

    WITH REPLACEMENT, NO finite-population correction. S-2.3, and it is what
    reproduces Barnett's published figure. An fpc here would quietly shrink
    every interval this tool prints.

    s_h^2 carries the (n_h - 1) denominator because that is the sample variance
    R survey computes, and the fixtures this was written against came from
    survey. Checked to 4 significant digits or better against every estimation
    fixture in `r/fixtures/stratified.json`.
    """
    if not weights:
        raise Refusal(
            Reason.STRATA_UNDEFINED,
            "No strata to estimate from.",
            "Check the plan's strata block.",
        )
    if not (len(weights) == len(positives) == len(sampled)):
        raise Refusal(
            Reason.LABELS_UNMATCHED,
            f"{len(weights)} strata, {len(positives)} positive counts and "
            f"{len(sampled)} sample sizes do not line up.",
            "The labels do not correspond to the drawn sample. Re-run ingest-labels.",
        )

    for index, count in enumerate(sampled):
        if count == 0:
            raise Refusal(
                Reason.STRATUM_UNSAMPLED,
                f"Stratum {index} received no sampled units, so it contributes no "
                "information and the estimate would silently omit part of the "
                "population.",
                "Check the sample: a stratum in the plan drew nothing. Re-run "
                "sample, or fix the plan's strata.",
            )
        if count < MIN_UNITS_PER_STRATUM:
            raise Refusal(
                Reason.ALLOCATION_TOO_THIN,
                f"Stratum {index} has {count} sampled unit, so its within-stratum "
                "variance is undefined.",
                "A stratum needs at least 2 sampled units for its variance to be "
                "defined. Re-plan with a larger sample_size.",
            )

    point = 0.0
    variance = 0.0
    for weight, hits, count in zip(weights, positives, sampled, strict=True):
        share = hits / count
        point += weight * share
        # n/(n-1) * p(1-p) is the sample variance of a 0/1 variable.
        sample_variance = (count / (count - 1)) * share * (1 - share)
        variance += weight * weight * sample_variance / count

    return StratifiedEstimate(
        point=point,
        standard_error=sqrt(variance),
        n=sum(sampled),
        positives=sum(positives),
        degrees_of_freedom=sum(sampled) - len(sampled),
    )
